apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "chart.fullname" . }}-deployment
  labels:
    app: {{ template "chart.fullname" . }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ template "chart.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "chart.fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.deploySecrets }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ template "chart.fullname" . }}
        envFrom:
        - configMapRef:
            name: {{ template "chart.fullname" . }}-env
        - secretRef:
            name: {{ template "chart.fullname" . }}-secret
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/os: linux
      imagePullSecrets:
      - name: {{ template "chart.fullname" . }}-docker-secret
